import math
import numpy as np
from typing import Dict, List, Tuple, Any
from src.core import PowerComponent


class GenTpj(PowerComponent):
    """
    Round Rotor Generator Model (GENTPJ) with armature-current-dependent saturation.

    GENTPJ is identical to GENTPF in all respects except that the saturation
    function argument is augmented by a term proportional to armature current
    magnitude, controlled by the parameter Kis (also written K_is):

        psi_eff = psi_ag + Kis * sqrt(Id^2 + Iq^2)

    This accounts for the leakage flux in the stator teeth generated by high
    stator currents, which increases the reluctance of the magnetic circuit.
    When Kis = 0 the model reduces exactly to GENTPF.

    State vector (same as GENTPF):
        x = [delta, omega, E''q, E'q, E'd, E''d]

    Physics reference:
        D.W. Olive (1966, 1968), J. Undrill WECC note (2007/2012),
        PowerWorld GENTPF/GENTPJ document (Weber, 2015), Section 3.3.

    Port-Hamiltonian interpretation
    --------------------------------
    The Kis term modifies the effective saturation argument at each time step.
    The PH structure (J, R, g matrices) is identical to GENTPF; the only change
    is that the saturation factors Sat_d and Sat_q are evaluated at
    psi_ag + Kis*|I| rather than psi_ag alone.  All passivity proofs carry over
    since Kis ≥ 0 ensures Sat_d, Sat_q ≥ 1 still holds.
    """

    @property
    def port_schema(self) -> Dict[str, List[Tuple[str, str, str]]]:
        return {
            'in': [
                ('Vd',  'effort', 'pu'),
                ('Vq',  'effort', 'pu'),
                ('Tm',  'effort', 'pu'),
                ('Efd', 'effort', 'pu'),
            ],
            'out': [
                ('Id',    'flow', 'pu'),
                ('Iq',    'flow', 'pu'),
                ('omega', 'flow', 'pu'),
                ('Pe',    'flow', 'pu'),
                ('Qe',    'flow', 'pu'),
                ('id_dq', 'flow', 'pu'),
                ('iq_dq', 'flow', 'pu'),
                ('It_Re', 'flow', 'pu'),
                ('It_Im', 'flow', 'pu'),
            ],
        }

    @property
    def state_schema(self) -> List[str]:
        return ['delta', 'omega', 'E_q_pp', 'E_q_prime', 'E_d_prime', 'E_d_pp']

    @property
    def param_schema(self) -> Dict[str, str]:
        return {
            'H':                'Inertia constant',
            'D':                'Damping coefficient',
            'ra':               'Stator resistance',
            'xd':               'd-axis synchronous reactance',
            'xq':               'q-axis synchronous reactance',
            'xd_prime':         'd-axis transient reactance',
            'xq_prime':         'q-axis transient reactance',
            'xd_double_prime':  'd-axis sub-transient reactance',
            'xq_double_prime':  'q-axis sub-transient reactance',
            'Td0_prime':        'd-axis transient open-circuit time constant',
            'Tq0_prime':        'q-axis transient open-circuit time constant',
            'Td0_double_prime': 'd-axis sub-transient open-circuit time constant',
            'Tq0_double_prime': 'q-axis sub-transient open-circuit time constant',
            'xl':               'Leakage reactance',
            'A_sat':            'Saturation coefficient A (scaled-quadratic)',
            'B_sat':            'Saturation coefficient B (scaled-quadratic)',
            # THE KEY GENTPJ PARAMETER:
            'Kis':              'Armature current saturation factor (Kis; set 0 for GENTPF)',
            'omega_b':          'Base frequency [rad/s]',
        }

    @property
    def observables(self) -> Dict[str, Dict[str, str]]:
        return {
            'delta_deg': {
                'description': 'Rotor angle',
                'unit': 'deg',
                'cpp_expr': 'x[0] * 180.0 / 3.14159265359',
            },
            'Te': {
                'description': 'Electrical torque',
                'unit': 'pu',
                'cpp_expr': 'outputs[3]',
            },
            'Pe': {
                'description': 'Active power',
                'unit': 'pu',
                'cpp_expr': 'outputs[3]',
            },
            'Qe': {
                'description': 'Reactive power',
                'unit': 'pu',
                'cpp_expr': 'outputs[4]',
            },
            'V_term': {
                'description': 'Terminal voltage',
                'unit': 'pu',
                'cpp_expr': 'sqrt(inputs[0]*inputs[0] + inputs[1]*inputs[1])',
            },
        }

    # ------------------------------------------------------------------
    #  Saturation helper
    # ------------------------------------------------------------------

    @staticmethod
    def _sat_coeffs_from_s(S10: float, S12: float):
        if S10 <= 0.0 or S12 <= 0.0:
            return 0.0, 0.0
        ratio = math.sqrt(1.2 * S12 / S10)
        if abs(ratio - 1.0) < 1e-10:
            return 0.0, 0.0
        u = 0.2 / (ratio - 1.0)
        return 1.0 - u, S10 / (u * u)

    def _sat_value(self, psi_eff: float) -> float:
        A = self.params.get('A_sat', 0.0)
        B = self.params.get('B_sat', 0.0)
        if psi_eff <= A or psi_eff < 1e-6 or B <= 0.0:
            return 0.0
        return B * (psi_eff - A) ** 2 / psi_eff

    # ------------------------------------------------------------------
    #  compute_outputs: Norton injection (same as GENTPF, no Kis needed
    #  here since terminal voltage is unknown — use nominal sat)
    # ------------------------------------------------------------------

    def get_cpp_compute_outputs_code(self) -> str:
        return r"""
            double delta  = x[0];
            double sin_d  = sin(delta);
            double cos_d  = cos(delta);

            double Eq_pp  = x[2];
            double Ed_pp  = x[5];

            double psi_d_pp_no =  Eq_pp;
            double psi_q_pp_no = -Ed_pp;
            double det   = ra*ra + xd_double_prime * xq_double_prime;
            double id_no = (-ra * psi_q_pp_no + xq_double_prime * psi_d_pp_no) / det;
            double iq_no = ( xd_double_prime * psi_q_pp_no + ra * psi_d_pp_no) / det;

            double I_Re =  id_no * sin_d + iq_no * cos_d;
            double I_Im = -id_no * cos_d + iq_no * sin_d;

            outputs[0] = I_Re;
            outputs[1] = I_Im;
            outputs[2] = x[1];
            outputs[3] = 0.0;
            outputs[4] = 0.0;
            outputs[5] = id_no;
            outputs[6] = iq_no;
            outputs[7] = I_Re;
            outputs[8] = I_Im;
        """

    def get_cpp_step_code(self) -> str:
        # Identical to GENTPF except psi_eff = psi_ag + Kis*sqrt(id^2+iq^2)
        return r"""
            double V_Re = inputs[0];
            double V_Im = inputs[1];
            double Tm   = inputs[2];
            double Efd  = inputs[3];

            double delta  = x[0];
            double omega  = x[1];
            double Eq_pp  = x[2];
            double Eq_p   = x[3];
            double Ed_p   = x[4];
            double Ed_pp  = x[5];

            double sin_d = sin(delta);
            double cos_d = cos(delta);

            double vd = V_Re * sin_d - V_Im * cos_d;
            double vq = V_Re * cos_d + V_Im * sin_d;

            // ---- Pass 1: unsaturated stator solve ----
            {
                double det1  = ra*ra + xd_double_prime * xq_double_prime;
                double b1    = Eq_pp * (1.0 + omega) - vq;
                double b2    = vd - Ed_pp * (1.0 + omega);
                double id    = ( xq_double_prime * b1 + ra * b2) / det1;
                double iq    = (-ra * b1 + xd_double_prime * b2) / det1;

                // Air-gap flux
                double psi_ag_d = vq + iq * ra + id * xl;
                double psi_ag_q = vd + id * ra - iq * xl;
                double psi_ag   = sqrt(psi_ag_d*psi_ag_d + psi_ag_q*psi_ag_q);

                // GENTPJ: augmented saturation argument with armature current
                double I_mag   = sqrt(id*id + iq*iq);
                double psi_eff = psi_ag + Kis * I_mag;

                double sat_val = 0.0;
                if (psi_eff > A_sat && psi_eff > 1e-6) {
                    double diff = psi_eff - A_sat;
                    sat_val = B_sat * diff * diff / psi_eff;
                }
                double Sat_d = 1.0 + sat_val;
                double Sat_q = 1.0 + (xq / xd) * sat_val;

                // Saturated subtransient reactances
                double Xd_pp_sat = (xd_double_prime - xl) / Sat_d + xl;
                double Xq_pp_sat = (xq_double_prime - xl) / Sat_q + xl;
                double det2  = Xd_pp_sat * Xq_pp_sat + ra * ra;

                // Refined stator solve
                id = ( Xq_pp_sat * b1 + ra * b2) / det2;
                iq = (-ra * b1 + Xd_pp_sat * b2) / det2;

                // Refine saturation with better id/iq
                I_mag   = sqrt(id*id + iq*iq);
                psi_ag_d = vq + iq * ra + id * xl;
                psi_ag_q = vd + id * ra - iq * xl;
                psi_ag   = sqrt(psi_ag_d*psi_ag_d + psi_ag_q*psi_ag_q);
                psi_eff  = psi_ag + Kis * I_mag;
                sat_val  = 0.0;
                if (psi_eff > A_sat && psi_eff > 1e-6) {
                    double diff = psi_eff - A_sat;
                    sat_val = B_sat * diff * diff / psi_eff;
                }
                Sat_d = 1.0 + sat_val;
                Sat_q = 1.0 + (xq / xd) * sat_val;

                double Te = Eq_pp * iq - (-Ed_pp) * id;

                // ---- State derivatives (same structure as GENTPF) ----
                dxdt[0] = omega_b * (omega - 1.0);
                dxdt[1] = (Tm - Te - D * (omega - 1.0)) / (2.0 * H);

                dxdt[2] = (Sat_d * (Eq_p - Eq_pp) - (xd_prime - xl) * id) / Td0_double_prime;

                double coeff_qq = (xd - xd_double_prime) / (xd_prime - xd_double_prime);
                double coeff_qp = (xd - xd_prime)        / (xd_prime - xd_double_prime);
                dxdt[3] = (Efd + Sat_q * (-coeff_qq * Eq_p + coeff_qp * Eq_pp)) / Td0_prime;

                double coeff_dq = (xq - xq_double_prime) / (xq_prime - xq_double_prime);
                double coeff_dp = (xq - xq_prime)        / (xq_prime - xq_double_prime);
                dxdt[4] = Sat_d * (-coeff_dq * Ed_p + coeff_dp * Ed_pp) / Tq0_prime;

                dxdt[5] = (Sat_d * (Ed_p - Ed_pp) + (xq_prime - xl) * iq) / Tq0_double_prime;

                outputs[3] = vd*id + vq*iq;
                outputs[4] = vq*id - vd*iq;
                outputs[5] = id;
                outputs[6] = iq;
                outputs[7] = id * sin_d + iq * cos_d;
                outputs[8] = -id * cos_d + iq * sin_d;
            }
        """

    # ------------------------------------------------------------------
    # Initialization (same logic as GENTPF, with Kis adjustment)
    # ------------------------------------------------------------------

    @property
    def component_role(self) -> str:
        return 'generator'

    def compute_norton_current(self, x_slice: np.ndarray) -> complex:
        p     = self.params
        delta = x_slice[0]
        Eq_pp = x_slice[2]
        Ed_pp = x_slice[5]
        ra    = p.get('ra', 0.0)
        xd_pp = p['xd_double_prime']
        xq_pp = p['xq_double_prime']

        psi_d_pp = Eq_pp
        psi_q_pp = -Ed_pp
        det   = ra**2 + xd_pp * xq_pp
        id_no = (-ra * psi_q_pp + xq_pp * psi_d_pp) / det
        iq_no = (xd_pp * psi_q_pp + ra * psi_d_pp) / det
        sin_d = math.sin(delta); cos_d = math.cos(delta)
        return complex(id_no * sin_d + iq_no * cos_d,
                       -id_no * cos_d + iq_no * sin_d)

    def init_from_phasor(self, V_phasor: complex, I_phasor: complex) -> tuple:
        p     = self.params
        ra    = p.get('ra', 0.0)
        xd    = p['xd'];   xq    = p['xq']
        xd_p  = p['xd_prime'];   xq_p  = p['xq_prime']
        xd_pp = p['xd_double_prime']; xq_pp = p['xq_double_prime']
        xl    = p['xl']
        Kis   = p.get('Kis', 0.0)

        Eq_phasor = V_phasor + (ra + 1j * xq) * I_phasor
        delta = float(np.angle(Eq_phasor))

        dq = np.exp(-1j * (delta - math.pi / 2))
        vd = float((V_phasor * dq).real)
        vq = float((V_phasor * dq).imag)
        id_val = float((I_phasor * dq).real)
        iq_val = float((I_phasor * dq).imag)

        I_mag    = math.sqrt(id_val**2 + iq_val**2)
        psi_ag_d = vq + iq_val * ra + id_val * xl
        psi_ag_q = vd + id_val * ra - iq_val * xl
        psi_ag   = math.sqrt(psi_ag_d**2 + psi_ag_q**2)
        psi_eff  = psi_ag + Kis * I_mag
        sat_val  = self._sat_value(psi_eff)
        Sat_d    = 1.0 + sat_val
        Sat_q    = 1.0 + (xq / xd) * sat_val

        Xd_pp_sat = (xd_pp - xl) / Sat_d + xl
        Xq_pp_sat = (xq_pp - xl) / Sat_q + xl

        Eq_pp = vq + ra * iq_val + Xd_pp_sat * id_val
        Ed_pp = -(vd + ra * id_val - Xq_pp_sat * iq_val)

        Eq_p = Eq_pp + (xd_p - xl) * id_val / Sat_d
        Ed_p = Ed_pp - (xq_p - xl) * iq_val / Sat_d

        coeff_qq = (xd - xd_pp) / (xd_p - xd_pp)
        coeff_qp = (xd - xd_p)  / (xd_p - xd_pp)
        Efd_req  = Sat_q * (coeff_qq * Eq_p - coeff_qp * Eq_pp)
        Tm_req   = vd * id_val + vq * iq_val

        targets = {
            'Efd': float(Efd_req), 'Tm': float(Tm_req),
            'Vt':  float(abs(V_phasor)),
            'omega': 1.0,
            'vd': vd, 'vq': vq,
            'id': id_val, 'iq': iq_val,
            'vd_ri': float(V_phasor.real),
            'vq_ri': float(V_phasor.imag),
        }
        return np.array([delta, 1.0, Eq_pp, Eq_p, Ed_p, Ed_pp]), targets

    def refine_at_kron_voltage(self, x_slice: np.ndarray,
                                vd: float, vq: float) -> np.ndarray:
        x  = x_slice.copy()
        p  = self.params
        ra = p.get('ra', 0.0)
        xd_pp = p['xd_double_prime']; xq_pp = p['xq_double_prime']
        xd_p  = p['xd_prime'];        xq_p  = p['xq_prime']
        xd    = p['xd'];              xq    = p['xq']
        xl    = p['xl'];              Kis   = p.get('Kis', 0.0)

        Eq_pp = x[2]; Ed_pp = x[5]
        det   = ra**2 + xd_pp * xq_pp
        b1    = Eq_pp - vq
        b2    = vd - Ed_pp
        id_est = (xq_pp * b1 + ra * b2) / det
        iq_est = (-ra * b1 + xd_pp * b2) / det

        I_mag    = math.sqrt(id_est**2 + iq_est**2)
        psi_ag_d = vq + iq_est * ra + id_est * xl
        psi_ag_q = vd + id_est * ra - iq_est * xl
        psi_ag   = math.sqrt(psi_ag_d**2 + psi_ag_q**2)
        psi_eff  = psi_ag + Kis * I_mag
        sat_val  = self._sat_value(psi_eff)
        Sat_d    = 1.0 + sat_val

        x[3] = Eq_pp + (xd_p - xl) * id_est / Sat_d
        x[4] = Ed_pp - (xq_p - xl) * iq_est / Sat_d
        return x

    def refine_d_axis(self, x_slice: np.ndarray, vd: float, vq: float,
                       Efd_eff: float, clamped: bool = False) -> np.ndarray:
        x  = x_slice.copy()
        p  = self.params
        xd    = p['xd'];   xd_p = p['xd_prime']; xd_pp = p['xd_double_prime']
        xq_pp = p['xq_double_prime'];  xl = p['xl'];  Kis = p.get('Kis', 0.0)
        ra    = p.get('ra', 0.0)

        Eq_pp = x[2]; Ed_pp = x[5]
        det   = ra**2 + xd_pp * xq_pp
        b1    = Eq_pp - vq
        b2    = vd - Ed_pp
        id_est = (xq_pp * b1 + ra * b2) / det
        iq_est = (-ra * b1 + xd_pp * b2) / det

        I_mag    = math.sqrt(id_est**2 + iq_est**2)
        psi_ag_d = vq + iq_est * ra + id_est * xl
        psi_ag_q = vd + id_est * ra - iq_est * xl
        psi_ag   = math.sqrt(psi_ag_d**2 + psi_ag_q**2)
        psi_eff  = psi_ag + Kis * I_mag
        sat_val  = self._sat_value(psi_eff)
        Sat_d    = 1.0 + sat_val
        Sat_q    = 1.0 + (p['xq'] / p['xd']) * sat_val

        coeff_qq = (xd - xd_pp) / (xd_p - xd_pp)
        coeff_qp = (xd - xd_p)  / (xd_p - xd_pp)
        if abs(Sat_q * coeff_qq) > 1e-10:
            Eq_p_new = (Efd_eff / Sat_q + coeff_qp * Eq_pp) / coeff_qq
        else:
            Eq_p_new = x[3]
        x[3] = Eq_p_new
        x[2] = Eq_p_new - (xd_p - xl) * id_est / Sat_d
        return x
